### ISSUE TITLE
where can i use this

### ISSUE THREAD

**Issue by dragonGRaf** [ZacharyHampton/PragmaticBlackjack#5]
on what websites can i use this

**Comment by ZacharyHampton** [comment]
> on what websites can i use this

I know you can use it on Stake, but I know there are plenty of other online casinos that use the same platform.

**Comment by dragonGRaf** [comment]
> > on what websites can i use this
> 
> I know you can use it on Stake, but I know there are plenty of other online casinos that use the same platform.

and how would i use this? 
how can i use it that i can win on these websites?

**Comment by ZacharyHampton** [comment]
> > > on what websites can i use this
> > 
> > 
> > I know you can use it on Stake, but I know there are plenty of other online casinos that use the same platform.
> 
> and how would i use this? how can i use it that i can win on these websites?

Develop algo and utilize library to interact with the blackjack game.
