### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Mert-Zengin** [ZacharyHampton/PragmaticBlackjack#6]
Can you share example how to use when i run it i get errorPS 
G:\BJ> python main.py
Connected.
{'dealer': {'@id': '7nfofhj3mk9jp7wp', '@seq': '2', '#text': 'Alexzander'}}
{'seat': {'@casino_id': 'ppcdg00000004311', '@country_code': 'NL', '@screen_name': 'Emoooo', '@user_id': 'ppc1699152308421', '@casino_name': 'PP DUX Brunocasino', '@num': '1', '@event': 'sit', '@table_id': 'sobj2710blackjac', '@enrollment_date': 'Sun Nov 05 00:00:00 UTC 2023', '@currency_code': 'EUR', '@sidebets': 'false', '@seq': '3', '#text': '266681627340110237 266681627340110237'}}
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<PragmaticController._handle_data() done, defined at G:\BJ\pragmatic\controller.py:18> exception=TypeError("'NoneType' object does not support item assignment")>

**Comment by Nyertes** [comment]
[Uploading Kibontva documents (7).pdf.pdf…]()


> Can you share example how to use when i run it i get errorPS G:\BJ> python main.py Connected. {'dealer': {'@id': '7nfofhj3mk9jp7wp', '@seq': '2', '#text': 'Alexzander'}} {'seat': {'@casino_id': 'ppcdg00000004311', '@country_code': 'NL', '@screen_name': 'Emoooo', '@user_id': 'ppc1699152308421', '@casino_name': 'PP DUX Brunocasino', '@num': '1', '@event': 'sit', '@table_id': 'sobj2710blackjac', '@enrollment_date': 'Sun Nov 05 00:00:00 UTC 2023', '@currency_code': 'EUR', '@sidebets': 'false', '@seq': '3', '#text': '266681627340110237 266681627340110237'}} Task exception was never retrieved future: <Task finished name='Task-2' coro=<PragmaticController._handle_data() done, defined at G:\BJ\pragmatic\controller.py:18> exception=TypeError("'NoneType' object does not support item assignment")>

**Comment by Nyertes** [comment]
`[](url)`

**Comment by Nyertes** [comment]
> `[](url)`

921813

**Comment by Mert-Zengin** [comment]
> > `[](url)`
> 
> 921813

what is that

**Comment by ZacharyHampton** [comment]
We really never added response handling, if you could add a PR to fix, that would be great.
