### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by Prino1967** [ZacharyHampton/PragmaticBlackjack#7]
Hi, I am an investor who would like to use Pagmatic play roulette to generate 10% per hour through a strategy that yields over 90% positive events with a yield of almost 20% of the stake played. Would you be interested in developing a bot that accesses the tables and performs a data collection of the numbers that have come out (the last 500) and through the strategy make bets at the table?
I thank you in advance for your response.

Translated with DeepL.com (free version)

**Comment by ZacharyHampton** [comment]
Sure @Prino1967, email me at zachary@bunsly.com.
